# Generated by Django 4.0.4 on 2022-04-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="hashed_url",
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
